# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  Dir.chdir('..') do
    sh("./scripts/create_carthage_symlink.sh")
  end
  carthage(platform: "iOS,mac", cache_builds: true)
end

platform :mac do
  desc "Run Tests"
  lane :test do
    scan(scheme: "SBKit")
  end
end

platform :ios do
  desc "Run Tests"
  lane :test do
    scan(scheme: "Second Brain")
  end
end
