# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  carthage(platform: "iOS,mac", cache_builds: true)
end

platform :mac do
  desc "Run Tests"
  lane :test do
    scan(scheme: "SBKit")
  end
end

platform :ios do
  desc "Run Tests"
  lane :test do
    scan(scheme: "Second Brain")
  end

  desc "Deploy a new versiot to Testflight"
  lane :beta do
    app_identifier = "com.younata.Second-Brain"
    match(type: 'development', app_identifier: app_identifier, readonly: true)
    match(type: 'appstore', app_identifier: app_identifier, readonly: true)
    increment_build_number(xcodeproj: 'Second Brain.xcodeproj', build_number: build_number)
    gym(project: 'Second Brain.xcodeproj', scheme: "Second Brain", export_method: "app-store")
    pilot(distribute_external: false, changelog: `git log -1 --format='%B'`)
  end

  def build_number
    1 #latest_testflight_build_number(app_identifier: 'com.younata.Second-Brain') + 1
  end
end
